# 'version' sudah tidak relevan dan bisa dihapus
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: driveease-app
    container_name: driveease-app
    restart: unless-stopped
    working_dir: /var/www
    user: "root" # <--- TAMBAHKAN BARIS INI
    volumes:
      - ./:/var/www # <--- KEMBALIKAN BARIS INI
    environment:
      - DB_HOST=db
      - DB_DATABASE=driveease
      - DB_USERNAME=driveease
      - DB_PASSWORD=driveease
    depends_on:
      - db
  webserver:
    image: nginx:alpine
    container_name: driveease-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # Mount ini penting agar Nginx bisa melihat file yang sama dengan 'app'
      - ./:/var/www 
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: driveease-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: driveease
      MYSQL_USER: driveease
      MYSQL_PASSWORD: driveease
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: